# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [18]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [3]:
np.version.version

'1.21.5'

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [5]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [9]:
x.size * x.itemsize

80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [10]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [12]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [14]:
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [15]:
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [20]:
x=np.arange(0,9)
y=np.reshape(x,(3,3))
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [9]:
x=np.array(6)
x=[1,2,0,0,4,0]
x
for i in range(0,len(x)):
    if x[i] != 0:
        print(i)


0
1
4


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [10]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [11]:
x = np.random.random((3,3,3))
print(x)

[[[0.03116973 0.59944935 0.73979155]
  [0.68721129 0.0067584  0.48827684]
  [0.4817332  0.08994117 0.42390741]]

 [[0.97506963 0.74004165 0.4197091 ]
  [0.27480316 0.52189078 0.47082805]
  [0.81139753 0.44290578 0.75860047]]

 [[0.32893484 0.20279688 0.40458519]
  [0.46141773 0.71446741 0.46321431]
  [0.93993064 0.04627566 0.82399466]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [15]:
x = np.random.random((10,10))
print(np.min(x))
print(np.max(x))

0.019731198090741975
0.9911873434286419


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [16]:
x = np.random.random(10)
print(x.mean())

0.3899587150215727


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [17]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [10]:
x = np.ones((5,5))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
x

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
nan
False
False
nan
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [21]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [23]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [29]:
print(np.unravel_index(99,(6,7,8)))
x = np.random.random((6,7,8))
print("The 100th Element: ",x[1,5,3])

(1, 5, 3)
The 100th Element:  0.6298965760810562
0.6298965760810562


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [30]:
x=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [31]:
x=np.random.rand(5,5)
print(x)
x=(x-np.mean(x))/(np.std(x))
print(x)

[[0.68330586 0.09845798 0.94656397 0.37338105 0.55610544]
 [0.02062127 0.20419926 0.38711338 0.44149803 0.97131373]
 [0.39730018 0.79426979 0.90122387 0.05614405 0.10258255]
 [0.39712275 0.11228981 0.31025974 0.08084658 0.39069165]
 [0.65251854 0.13513861 0.23429404 0.87333201 0.95872178]]
[[ 0.76509855 -1.09830364  1.60387346 -0.22236262  0.35982131]
 [-1.34630163 -0.76139801 -0.17860961 -0.00533297  1.68272945]
 [-0.14615312  1.11864419  1.45941397 -1.23312136 -1.0851622 ]
 [-0.14671845 -1.05423361 -0.42347541 -1.15441587 -0.16720877]
 [ 0.66700609 -0.98143431 -0.66551209  1.37054683  1.64260984]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [37]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [33]:
a=np.random.rand(5,3)
print(a)
b=np.random.rand(3,2)
print(b)
c=np.dot(a,b)
print(c)

[[0.12375148 0.80079776 0.26910205]
 [0.31828002 0.11835777 0.68689314]
 [0.77628211 0.42069121 0.66117717]
 [0.34029999 0.38451522 0.25239577]
 [0.91480896 0.06988819 0.96311791]]
[[0.75947297 0.40190357]
 [0.10516639 0.93269509]
 [0.12494628 0.3122499 ]]
[[0.21182621 0.88066338]
 [0.33999707 0.4527919 ]
 [0.71641948 0.91081968]
 [0.33042263 0.57421379]
 [0.82246057 0.73358283]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [39]:
arr = np.arange(16)
arr[(arr>=3) & (arr<=8)]*=(-1)
print(arr)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [48]:
Z<Z>Z

False

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan
0
array

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [49]:
x = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(x)), x))

[ -8.  -3.  -4. -10.  -9.   1.  -3.   6.   4.  -9.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [50]:
x = np.random.randint(0,10,10)
y = np.random.randint(0,10,10)
print(np.intersect1d(x,y))

[1 4 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [51]:
defaults = np.seterr(all="ignore")
x = np.ones(1) / 0

In [52]:
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [54]:
yesterday = np.datetime64('today') - np.timedelta64(1)
print(yesterday)
today     = np.datetime64('today')
print(today)
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(tomorrow)

2023-01-02
2023-01-03
2023-01-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [55]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [65]:
A = np.ones(3)*1
print(A)
B = np.ones(3)*2
print(B)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)

[1. 1. 1.]
[2. 2. 2.]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [67]:
x = np.random.uniform(0,10,10)
print(x)
print(x - x%1)
print(x // 1)
print(np.floor(x))
print(x.astype(int))
print(np.trunc(x))

[6.84327512 0.83091383 4.22343471 5.32774253 2.9151212  3.98046546
 8.23083701 9.84011408 5.35746483 7.56000702]
[6. 0. 4. 5. 2. 3. 8. 9. 5. 7.]
[6. 0. 4. 5. 2. 3. 8. 9. 5. 7.]
[6. 0. 4. 5. 2. 3. 8. 9. 5. 7.]
[6 0 4 5 2 3 8 9 5 7]
[6. 0. 4. 5. 2. 3. 8. 9. 5. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [73]:
x = np.zeros((5,5))
print(x)
x = x + np.arange(5)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [75]:
def generate():
    for x in range(10):
        yield x
x = np.fromiter(generate(),dtype=float,count=-1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [76]:
x = np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [77]:
x = np.random.random(10)
print(x)
x.sort()
print(x)

[0.35070103 0.72449066 0.45425307 0.69866159 0.19337098 0.81482551
 0.46364507 0.33289447 0.09736375 0.76613093]
[0.09736375 0.19337098 0.33289447 0.35070103 0.45425307 0.46364507
 0.69866159 0.72449066 0.76613093 0.81482551]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [79]:
x = np.random.randint(0,20,10)
print(x)
np.add.reduce(x)

[ 5  4 15 13  6  7  9  1  3 12]


75

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [83]:
x = np.random.randint(0,10,5)
y = np.random.randint(0,10,5)
print(x)
print(y)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(x,y)
print(equal)
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(x,y)
print(equal)

[2 0 3 6 4]
[8 4 7 3 0]
False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [85]:
x = np.zeros(10)
x.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [92]:
x = np.random.randint(0,60,10)
print(x)
print("Max value is at index {} and the value is {} ". format(x.argmax(),x.max()))
x[x.argmax()] = 0
print(x)

[40 27 40 48 54 47 18  2  8  3]
Max value is at index 4 and the value is 54 
[40 27 40 48  0 47 18  2  8  3]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [97]:
for dtype in [np.int8, np.int32, np.int64]:
    print("Min value for dtype {} is {} ". format(dtype,np.iinfo(dtype).min))
    print("Max value for dtype {} is {} ". format(dtype,np.iinfo(dtype).max))
for dtype in [np.float32, np.float64]:
    print("Min value for dtype {} is {} ". format(dtype,np.finfo(dtype).min))
    print("Max value for dtype {} is {} ". format(dtype,np.finfo(dtype).max))
    print("Epsilon value for dtype {} is {} ". format(dtype,np.finfo(dtype).eps))

Min value for dtype <class 'numpy.int8'> is -128 
Max value for dtype <class 'numpy.int8'> is 127 
Min value for dtype <class 'numpy.int32'> is -2147483648 
Max value for dtype <class 'numpy.int32'> is 2147483647 
Min value for dtype <class 'numpy.int64'> is -9223372036854775808 
Max value for dtype <class 'numpy.int64'> is 9223372036854775807 
Min value for dtype <class 'numpy.float32'> is -3.4028234663852886e+38 
Max value for dtype <class 'numpy.float32'> is 3.4028234663852886e+38 
Epsilon value for dtype <class 'numpy.float32'> is 1.1920928955078125e-07 
Min value for dtype <class 'numpy.float64'> is -1.7976931348623157e+308 
Max value for dtype <class 'numpy.float64'> is 1.7976931348623157e+308 
Epsilon value for dtype <class 'numpy.float64'> is 2.220446049250313e-16 


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [106]:
np.set_printoptions(threshold=float("inf"))
x = np.random.rand(5,3)
print(x)

[[0.475085   0.38329153 0.0927911 ]
 [0.27835365 0.35202618 0.91442086]
 [0.11895647 0.01736506 0.41704384]
 [0.25291372 0.93109816 0.31589547]
 [0.16854701 0.46491077 0.20599472]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [109]:
x = np.arange(10)
print(x)
v = np.random.uniform(0,10)
print(v)
index = (np.abs(x-v)).argmin()
print(x[index])

[0 1 2 3 4 5 6 7 8 9]
4.266376268834228
4


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [110]:
x = (np.random.rand(10)*100).astype(np.float32)
print(x)
y = x.view(np.int32)
y[:] = x
print(Y)

[77.420364 82.23153  11.58049  71.06005  21.45045  42.212467 12.915757
 66.492424 20.796423 62.633175]
[0.59192785 0.69009803 0.26523866 0.88098984 0.05147803 0.88414581
 0.24186672 0.28646976 0.95635634 0.31084471]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [111]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11''')
dt = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(dt)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\sampathkumar.g\AppData\Local\Temp\ipykernel_19424\990613357.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dt = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [114]:
x = np.arange(4).reshape(2,2)
for index, value in np.ndenumerate(x):
    print(index, value)
for index in np.ndindex(x.shape):
    print(index, x[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [115]:
n = 10
p = 3
x = np.zeros((n,n))
np.put(x, np.random.choice(range(n*n), p, replace=False),1)
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [118]:
x = np.random.rand(2, 3)
print(x)
y = x - x.mean(axis=1, keepdims=True)
print(y)

[[0.27028988 0.39262338 0.96051336]
 [0.19411693 0.57159761 0.89922255]]
[[-0.27085233 -0.14851883  0.41937115]
 [-0.3608621   0.01661858  0.34424352]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [119]:
x = np.random.randint(0,10,(3,3))
print(x)
print(x[x[:,1].argsort()])

[[2 9 5]
 [1 8 1]
 [5 9 0]]
[[1 8 1]
 [2 9 5]
 [5 9 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [123]:
x = np.random.randint(0,2,(4,4))
print(x)
print((~x.any(axis=0)).any())

[[0 1 0 1]
 [0 0 1 0]
 [0 0 1 0]
 [1 0 1 1]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [125]:
x = np.random.uniform(0,1,10)
print(x)
y = 0.5
z = x.flat[np.abs(x - y).argmin()]
print(z)

[0.56744266 0.66195515 0.76300671 0.74327478 0.54180966 0.10533283
 0.12447887 0.62373692 0.35807943 0.6943371 ]
0.5418096566406816


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [126]:
x = np.arange(3).reshape(3,1)
print(x)
y = np.arange(3).reshape(1,3)
print(y)
it = np.nditer([x,y,None])
for a,b,c in it: c[...] = a + b
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [129]:
x = np.ones(10)
print(x)
y = np.random.randint(0,10,len(x))
print(y)
z += np.bincount(y, minlength=len(x))
print(z)

np.add.at(x,y,1)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 4 6 7 7 3 0 7 2]
[6.54180966 5.54180966 5.54180966 4.54180966 4.54180966 5.54180966
 4.54180966 6.54180966 5.54180966 6.54180966]
[2. 1. 2. 2. 2. 3. 2. 4. 1. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [130]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [131]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [132]:
x = np.random.randint(0,10,(3,4,3,4))
print(x)
sum = x.sum(axis=(-2,-1))
print(sum)

[[[[3 1 0 0]
   [4 1 1 4]
   [1 9 3 7]]

  [[7 8 9 9]
   [9 6 1 5]
   [2 1 4 2]]

  [[0 9 0 7]
   [6 6 4 4]
   [4 9 4 5]]

  [[6 6 1 9]
   [0 4 0 9]
   [4 6 8 2]]]


 [[[2 5 8 2]
   [2 7 2 3]
   [7 1 7 3]]

  [[4 7 2 5]
   [5 7 7 0]
   [5 5 4 8]]

  [[3 8 7 1]
   [5 7 4 3]
   [2 2 3 4]]

  [[5 1 9 1]
   [4 8 0 1]
   [3 4 2 2]]]


 [[[8 5 2 2]
   [8 1 6 2]
   [3 9 9 7]]

  [[9 5 0 7]
   [4 3 5 6]
   [2 9 5 1]]

  [[4 4 1 1]
   [8 5 1 5]
   [3 8 3 3]]

  [[5 8 9 9]
   [8 2 0 3]
   [9 4 2 9]]]]
[[34 63 58 55]
 [49 59 49 40]
 [62 56 46 68]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [133]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.57374178 0.44200415 0.61635102 0.42548429 0.4358125  0.4259439
 0.52388275 0.34203926 0.44926374 0.53605071]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [136]:
x = np.random.uniform(0,1,(2,2))
print(x)
y = np.random.uniform(0,1,(2,2))
print(y)
np.diag(np.dot(x, y))

[[0.75899005 0.24068665]
 [0.28572615 0.45110193]]
[[0.93370517 0.8751372 ]
 [0.83988061 0.40227634]]


array([0.91082098, 0.43151722])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [138]:
x = np.array([1,2,3,4,5])
print(x)
z = 3
x0 = np.zeros(len(x) + (len(x)-1)*(z))
x0[::z+1] = x
print(x0)

[1 2 3 4 5]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [139]:
x = np.ones((5,5,3))
print(x)
y = 2*np.ones((5,5))
print(y)
print(x * y[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [140]:
x = np.arange(25).reshape(5,5)
print(x)
x[[0,1]] = x[[1,0]]
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [141]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [143]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
x = np.arange(5)
print(x)
print(moving_average(x, n=3))

[0 1 2 3 4]
[1. 2. 3.]


In [144]:
from numpy.lib.stride_tricks import sliding_window_view
x = np.arange(5)
print(x)
print(sliding_window_view(x, window_shape=3).mean(axis=-1))

[0 1 2 3 4]
[1. 2. 3.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [145]:
x = np.arange(10)
print(x)
print(sliding_window_view(x, window_shape=3))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [148]:
x = np.random.randint(0,2,5)
print(x)
np.logical_not(x, out=x)

[1 1 1 1 0]


array([0, 0, 0, 0, 1])

In [149]:
x = np.random.uniform(-1.0,1.0,5)
print(x)
np.negative(x, out=x)

[ 0.06149843 -0.36143263  0.26230952 -0.11256214 -0.453226  ]


array([-0.06149843,  0.36143263, -0.26230952,  0.11256214,  0.453226  ])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [155]:
x = np.arange(1, 15, dtype=np.uint32)
print(x)
print(sliding_window_view(x, window_shape=4))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [159]:
x = np.random.uniform(0,1,(3,3))
print(x)
U, S, V = np.linalg.svd(x)
rank = np.sum(S > 1e-10)
print(rank)

[[0.12945469 0.54453345 0.28007576]
 [0.8603197  0.92426459 0.43750359]
 [0.75195598 0.94399861 0.07163512]]
3


In [158]:
x = np.random.uniform(0,1,(2,2))
print(x)
rank = np.linalg.matrix_rank(x)
print(rank)

[[0.7901129  0.81617042]
 [0.79899741 0.62265643]]
2


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [161]:
x = np.random.randint(0,3,10)
print(x)
print(np.bincount(x).argmax())

[0 0 1 1 2 0 1 0 1 1]
1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [162]:
x = np.random.randint(0,5,(10,10))
print(x)
print(sliding_window_view(x, window_shape=(3, 3)))

[[1 4 0 4 2 4 1 1 1 3]
 [3 2 1 1 0 1 1 3 0 4]
 [4 3 2 1 2 2 2 4 0 1]
 [4 0 3 4 4 2 3 4 3 2]
 [3 1 2 1 2 1 1 3 0 4]
 [4 3 1 0 0 3 3 1 2 2]
 [3 1 0 2 4 3 4 4 3 2]
 [0 4 2 3 0 0 3 4 1 2]
 [1 0 1 3 3 4 1 1 0 4]
 [3 2 4 0 0 4 0 4 2 2]]
[[[[1 4 0]
   [3 2 1]
   [4 3 2]]

  [[4 0 4]
   [2 1 1]
   [3 2 1]]

  [[0 4 2]
   [1 1 0]
   [2 1 2]]

  [[4 2 4]
   [1 0 1]
   [1 2 2]]

  [[2 4 1]
   [0 1 1]
   [2 2 2]]

  [[4 1 1]
   [1 1 3]
   [2 2 4]]

  [[1 1 1]
   [1 3 0]
   [2 4 0]]

  [[1 1 3]
   [3 0 4]
   [4 0 1]]]


 [[[3 2 1]
   [4 3 2]
   [4 0 3]]

  [[2 1 1]
   [3 2 1]
   [0 3 4]]

  [[1 1 0]
   [2 1 2]
   [3 4 4]]

  [[1 0 1]
   [1 2 2]
   [4 4 2]]

  [[0 1 1]
   [2 2 2]
   [4 2 3]]

  [[1 1 3]
   [2 2 4]
   [2 3 4]]

  [[1 3 0]
   [2 4 0]
   [3 4 3]]

  [[3 0 4]
   [4 0 1]
   [4 3 2]]]


 [[[4 3 2]
   [4 0 3]
   [3 1 2]]

  [[3 2 1]
   [0 3 4]
   [1 2 1]]

  [[2 1 2]
   [3 4 4]
   [2 1 2]]

  [[1 2 2]
   [4 4 2]
   [1 2 1]]

  [[2 2 2]
   [4 2 3]
   [2 1 1]]

  [[2 2 4]
   [2 3 4]
   [1 1 

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [171]:
x = np.ones((16,16))
print(x)
k = 4
print(sliding_window_view(x, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [174]:
x = random.randint(0,10,10)
print(x)
np.random.shuffle(x)
n = 5
print(x)

[2 8 9 1 5 5 2 1 8 9]
[8 5 9 5 2 1 8 9 2 1]


In [175]:
print (x[np.argsort(x)[-n:]])

[5 8 8 9 9]


In [176]:
print (x[np.argpartition(-x,n)[:n]])

[9 9 8 8 5]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [179]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [183]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.55 s ± 649 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
646 ms ± 47.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
355 ms ± 50.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [184]:
A = np.random.randint(0,5,(8,3))
print(A)
B = np.random.randint(0,5,(2,2))
print(B)
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[[2 3 0]
 [0 0 1]
 [1 1 2]
 [1 0 1]
 [3 3 4]
 [1 2 1]
 [3 0 1]
 [4 1 4]]
[[3 1]
 [3 2]]
[0 2 4 5 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [186]:
x = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(x[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [189]:
x = np.random.randint(0,2,(4,3))
print(x)
u = np.unique(x, axis=0)
print(u)

[[1 0 0]
 [1 0 0]
 [1 0 1]
 [1 0 1]]
[[1 0 0]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)